<a href="https://colab.research.google.com/github/samuelvalenciac/Ciencias_datos/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
# Numpy

import numpy as np

# 1. Arreglos

# 1.1 Listas

lista = np.array([5, 10, 15, 10, 25, 30])
print("Arreglo desde listas:", lista)
print("\n")

# 1.2 Matrices

matriz = np.array([[5,10,15,20],[25,30,35,40]])
print("Arreglo desde matrices:", matriz)
print("\n")

# 1.3 Rangos

rango = np.arange(0, 50, 5)
print("Arreglo con rangos:", rango)
print("\n")

# 1.4 Binario

cero = np.zeros((2,3))
uno = np.ones((4,2))
print("Arreglo de ceros:", cero)
print("\n")
print("Arreglo de unos:", uno)
print("\n")

# 1.5 Aleatorio

aleatorio = np.random.rand(3,2)
aleatorio_ent  = np.random.randint(5,50,(3,2))

print("Arreglo aleatorio:", aleatorio)
print("\n")
print("Arreglo aleatorio de enteros:", aleatorio_ent)

Arreglo desde listas: [ 5 10 15 10 25 30]


Arreglo desde matrices: [[ 5 10 15 20]
 [25 30 35 40]]


Arreglo con rangos: [ 0  5 10 15 20 25 30 35 40 45]


Arreglo de ceros: [[0. 0. 0.]
 [0. 0. 0.]]


Arreglo de unos: [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


Arreglo aleatorio: [[0.4189743  0.35492273]
 [0.46101194 0.55489656]
 [0.83372054 0.94354642]]


Arreglo aleatorio de enteros: [[30 11]
 [32 40]
 [34 36]]


In [25]:
# 2. Propiedades de los arreglos

# 2.1 Dimensiones

dimensiones = matriz.ndim
print("Numero de dimensiones:", dimensiones)
print("\n")

# 2.2 Forma

forma = matriz.shape
print("Forma:", forma)
print("\n")

# 2.3 Número de elementos

tamaño = matriz.size
print("Numero de elementos:", tamaño)
print("\n")

# 2.4Tipo de datos

tipo = matriz.dtype
print("Tipo de dato:", tipo)
print("\n")

Numero de dimensiones: 2


Forma: (2, 4)


Numero de elementos: 8


Tipo de dato: int64




In [26]:
# 3. Indexación y slicing

# 3.1 Arreglos

arreglo2 = np.array([5,10,15,20,30,25,40])
indice = arreglo2[4]
ind_rango = arreglo2[1:2]
slicing = arreglo2[::-1]

print("Índice:", indice)
print("Índice con rango:", ind_rango)
print("Slicing:", slicing)
print("\n")


# 3.2 Matrices

matriz2 = np.array([[5,10,15,20],[25,30,25,40]])
indice2 = matriz2[0,2]
indice_columna = matriz2[:,1]
indice_fila = matriz2[0,:]
submatriz = matriz2[1:2,2:3]

print("matriz:", matriz2)
print("indice:", indice2)
print("indice columna:", indice_columna)
print("indice fila:", indice_fila)
print("submatriz:", submatriz)

Índice: 30
Índice con rango: [10]
Slicing: [40 25 30 20 15 10  5]


matriz: [[ 5 10 15 20]
 [25 30 25 40]]
indice: 15
indice columna: [10 30]
indice fila: [ 5 10 15 20]
submatriz: [[25]]


In [27]:
# 4. Operaciones matemáticas

# 4.1 Básicas

suma = lista + 10
print("Suma:", suma)

mult = lista * 5
print("Multiplicación:", mult)

div = lista / 10
print("División:", div)

potencia = lista ** 3
print("Exponente:", potencia)

# 4.2 Operaciones entre arreglos

a = np.array([5,10,15,20])
b = np.array([25,30,35,40])

suma_arreglo = a + b
mult_arreglo = a * b
div_arreglo = a / b
pot_arreglo = a ** b

print("Suma de arreglos:", suma_arreglo)
print("Multiplicacion de arreglos:", mult_arreglo)
print("Division de arreglos:", div_arreglo)
print("Exponente de arreglos:", pot_arreglo)

Suma: [15 20 25 20 35 40]
Multiplicación: [ 25  50  75  50 125 150]
División: [0.5 1.  1.5 1.  2.5 3. ]
Exponente: [  125  1000  3375  1000 15625 27000]
Suma de arreglos: [30 40 50 60]
Multiplicacion de arreglos: [125 300 525 800]
Division de arreglos: [0.2        0.33333333 0.42857143 0.5       ]
Exponente de arreglos: [  298023223876953125  5076944270305263616 -7082734255363670225
                    0]


In [28]:
# 5. Funciones

raiz = np.sqrt(lista)
print("Raíz cuadrada:", raiz)

media = np.mean(lista)
print("Media:", media)

suma2 = np.sum(lista)
print("Suma:", suma2)

max = np.max(lista)
print("Máximo:", max)

min = np.min(lista)
print("Mínimo:", min)

des_est = np.std(lista)
print("Desviación estándar:", des_est)

Raíz cuadrada: [2.23606798 3.16227766 3.87298335 3.16227766 5.         5.47722558]
Media: 15.833333333333334
Suma: 95
Máximo: 30
Mínimo: 5
Desviación estándar: 8.858454843945541
